{ ... }:
{
	gtk = {
		enable = true;
		colorScheme = "dark";

		gtk3 = {
			enable = true;
			colorScheme = "dark";
			extraCss = ''
				@define-color accent_color #C98B73;
				@define-color accent_bg_color #C98B73;
				@define-color accent_fg_color #291510;
				@define-color destructive_bg_color #E6A29B;
				@define-color destructive_fg_color #3A1715;
				@define-color error_bg_color #E6A29B;
				@define-color error_fg_color #3A1715;
				@define-color window_bg_color #120C0B;
				@define-color window_fg_color #F1E9E4;
				@define-color view_bg_color #170F0E;
				@define-color view_fg_color #F1E9E4;
				@define-color headerbar_bg_color #120C0B;
				@define-color headerbar_fg_color #F1E9E4;
				@define-color headerbar_backdrop_color @window_bg_color;
				@define-color popover_bg_color #2B1B17;
				@define-color popover_fg_color #F1E9E4;
				@define-color card_bg_color #211513;
				@define-color card_fg_color #F1E9E4;
				@define-color dialog_bg_color #120C0B;
				@define-color dialog_fg_color #F1E9E4;
				@define-color overview_bg_color #211513;
				@define-color overview_fg_color #F1E9E4;
				@define-color sidebar_bg_color #211513;
				@define-color sidebar_fg_color #F1E9E4;
				@define-color sidebar_backdrop_color @window_bg_color;
				@define-color sidebar_border_color #493029;
				@define-color secondary_sidebar_bg_color #120C0B;
				@define-color secondary_sidebar_fg_color #D0C0B9;
				@define-color theme_unfocused_fg_color #D0C0B9;
				@define-color theme_unfocused_text_color #D0C0B9;
				@define-color theme_unfocused_bg_color #120C0B;
				@define-color theme_unfocused_base_color #170F0E;
				@define-color theme_unfocused_selected_bg_color #9F6C59;
				@define-color theme_unfocused_selected_fg_color #F8F0EB;
			'';
		};

		gtk4 = {
			enable = true;
			colorScheme = "dark";
			extraCss = ''
				@define-color accent_color #C98B73;
				@define-color accent_bg_color #C98B73;
				@define-color accent_fg_color #291510;
				@define-color destructive_bg_color #E6A29B;
				@define-color destructive_fg_color #3A1715;
				@define-color error_bg_color #E6A29B;
				@define-color error_fg_color #3A1715;
				@define-color window_bg_color #120C0B;
				@define-color window_fg_color #F1E9E4;
				@define-color view_bg_color #170F0E;
				@define-color view_fg_color #F1E9E4;
				@define-color headerbar_bg_color #120C0B;
				@define-color headerbar_fg_color #F1E9E4;
				@define-color headerbar_backdrop_color @window_bg_color;
				@define-color popover_bg_color #2B1B17;
				@define-color popover_fg_color #F1E9E4;
				@define-color card_bg_color #211513;
				@define-color card_fg_color #F1E9E4;
				@define-color dialog_bg_color #120C0B;
				@define-color dialog_fg_color #F1E9E4;
				@define-color overview_bg_color #211513;
				@define-color overview_fg_color #F1E9E4;
				@define-color sidebar_bg_color #211513;
				@define-color sidebar_fg_color #F1E9E4;
				@define-color sidebar_backdrop_color @window_bg_color;
				@define-color sidebar_border_color #493029;
				@define-color secondary_sidebar_bg_color #120C0B;
				@define-color secondary_sidebar_fg_color #D0C0B9;
				@define-color theme_unfocused_fg_color #D0C0B9;
				@define-color theme_unfocused_text_color #D0C0B9;
				@define-color theme_unfocused_bg_color #120C0B;
				@define-color theme_unfocused_base_color #170F0E;
				@define-color theme_unfocused_selected_bg_color #9F6C59;
				@define-color theme_unfocused_selected_fg_color #F8F0EB;
				
				:root {
					--accent-color: #C98B73;
					--accent-bg-color: #C98B73;
					--accent-fg-color: #291510;
					--destructive-bg-color: #E6A29B;
					--destructive-fg-color: #3A1715;
					--error-bg-color: #E6A29B;
					--error-fg-color: #3A1715;
					--error-color: #E6A29B;
					--window-bg-color: #120C0B;
					--window-fg-color: #F1E9E4;
					--view-bg-color: #170F0E;
					--view-fg-color: #F1E9E4;
					--headerbar-bg-color: #120C0B;
					--headerbar-fg-color: #F1E9E4;
					--headerbar-backdrop-color: #120C0B;
					--popover-bg-color: #2B1B17;
					--popover-fg-color: #F1E9E4;
					--card-bg-color: #211513;
					--card-fg-color: #F1E9E4;
					--dialog-bg-color: #120C0B;
					--dialog-fg-color: #F1E9E4;
					--overview-bg-color: #211513;
					--overview-fg-color: #F1E9E4;
					--sidebar-bg-color: #211513;
					--sidebar-fg-color: #F1E9E4;
					--sidebar-backdrop-color: #120C0B;
					--sidebar-border-color: #493029;
					--secondary-sidebar-bg-color: #120C0B;
					--secondary-sidebar-fg-color: #D0C0B9;
					--warning-bg-color: #4A321F;
					--warning-fg-color: #F1D5AC;
					--warning-color: #D9AE78;
					--success-color: #A8BF96;
					--success-bg-color: #293624;
					--success-fg-color: #DCE8D1;
					--shade-color: rgba(0, 0, 0, 0.45);
				}

				@define-color accent_color #C98B73;
				@define-color accent_bg_color #C98B73;
				@define-color accent_fg_color #291510;
				@define-color destructive_bg_color #E6A29B;
				@define-color destructive_fg_color #3A1715;
				@define-color error_bg_color #E6A29B;
				@define-color error_fg_color #3A1715;
				@define-color window_bg_color #120C0B;
				@define-color window_fg_color #F1E9E4;
				@define-color view_bg_color #170F0E;
				@define-color view_fg_color #F1E9E4;
				@define-color headerbar_bg_color #120C0B;
				@define-color headerbar_fg_color #F1E9E4;
				@define-color headerbar_backdrop_color @window_bg_color;
				@define-color popover_bg_color #2B1B17;
				@define-color popover_fg_color #F1E9E4;
				@define-color card_bg_color #211513;
				@define-color card_fg_color #F1E9E4;
				@define-color dialog_bg_color #120C0B;
				@define-color dialog_fg_color #F1E9E4;
				@define-color overview_bg_color #211513;
				@define-color overview_fg_color #F1E9E4;
				@define-color sidebar_bg_color #211513;
				@define-color sidebar_fg_color #F1E9E4;
				@define-color sidebar_backdrop_color @window_bg_color;
				@define-color sidebar_border_color #493029;
				@define-color secondary_sidebar_bg_color #120C0B;
				@define-color secondary_sidebar_fg_color #D0C0B9;
				@define-color theme_unfocused_fg_color #D0C0B9;
				@define-color theme_unfocused_text_color #D0C0B9;
				@define-color theme_unfocused_bg_color #120C0B;
				@define-color theme_unfocused_base_color #170F0E;
				@define-color theme_unfocused_selected_bg_color #9F6C59;
				@define-color theme_unfocused_selected_fg_color #F8F0EB;
			'';
		};
	};
}
