ipc = on
splash = false

wallpaper = , /home/george/Pictures/Wallpapers/paul-brennus-1.jpg
wallpaper[]:path = /home/george/Pictures/Wallpapers/paul-brennus-1.jpg

# wallpaper {
#    monitor = eDP-1
#    path = /home/george/Pictures/Wallpapers/paul-brennus-1.jpg
#    fit_mode = cover
# }

