ipc = on
splash = false

wallpaper = eDP-1, /home/george/Pictures/Wallpapers/paul-brennus-1.jpg, cover

# wallpaper {
#    monitor = eDP-1
#    path = /home/george/Pictures/Wallpapers/paul-brennus-1.jpg
#    fit_mode = cover
# }

