# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hyprpaper
exec-once = $bar
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = udiskie
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = syncthing serve
